### ISSUE TITLE
Massive and misaligned icons in GNOME 3.36

### ISSUE THREAD

**Issue by viggy96** [AlexPoilrouge/NordVPN-connect#12]
![Screenshot from 2020-03-25 16-22-22](https://user-images.githubusercontent.com/9837626/77581912-ed24c500-6eb4-11ea-8adc-13ed5a5146dc.png)
Basically the title. I've got the latest extension, but the issue persists.

**Comment by AlexPoilrouge** [comment]
Gnome 3.36?

Can you give me you're screen resolution?

**Comment by AlexPoilrouge** [comment]
It is possible that the display would be fixed at the next boot, or if you reload the shell using `alt+f2` and typing `r` ?

**Comment by viggy96** [comment]
I have tried rebooting and restarting the GNOME shell. My display resolution is 2560x1080.

**Comment by AlexPoilrouge** [comment]
Even with the latest css tweak made in today's last commit?

**Comment by viggy96** [comment]
Yes

**Comment by AlexPoilrouge** [comment]
Okay, I'm pretty confident that today's commit should fix this issue.

**Comment by viggy96** [comment]
Are the icons supposed to be huge? Because they're no longer misaligned, but they are still large.

**Comment by AlexPoilrouge** [comment]
This is the normal icon size, yes.

It's the new default style of buttons for gnome 3.34
![Sans titre](https://user-images.githubusercontent.com/2669900/77852915-77389a80-71e1-11ea-83b2-f185cba0e34e.png)
