### ISSUE TITLE
Improvement: No color background

### ISSUE THREAD

**Issue by thereallinusrg** [AlexPoilrouge/NordVPN-connect#14]
The option to turn off the colorful background would make the extension fit better into the else wise monochrome GNOME Status area.

Also this would be a (style wise) distinguishing factor from the other NordVPN  extensions on the GNOME extensions site.

**Comment by AlexPoilrouge** [comment]
“ Colorfull background ” ?

You mean not having the icon turn green in the top bar when connected ?

**Comment by thereallinusrg** [comment]
exactly

**Comment by AlexPoilrouge** [comment]
The option has been added into the latest commit.

Once up to date, you should find the 'colored status' toggle option within the extension's settings page.

**Comment by thereallinusrg** [comment]
Great, thank you!
