### ISSUE TITLE
Colored icon background after icon reload, disregarding the setting

### ISSUE THREAD

**Issue by thereallinusrg** [AlexPoilrouge/NordVPN-connect#16]
This is related to issue #14. 
First, thank you for adding that option.

I have the colored status setting set to off.
After a reconnect or after locking the desktop the colored background is back again.
The setting has to be re-toggled to make it transparent again.

I am on Gnome 3.36.1

**Comment by AlexPoilrouge** [comment]
You're right, thanks for reporting the bug.

It should be fixed now.
