### ISSUE TITLE
Country list makes a line break for 'W'

### ISSUE THREAD

**Issue by jgottlander** [AlexPoilrouge/NordVPN-connect#17]
When listing countries the 'W' character in the country names seems to make a line brake.

OS: Pop! OS 20.04
Gnome: 3.36.1 Wayland
Driver: Intel modesetting
Image: [Screenshot](https://imgur.com/a/y2NfF5c)

**Comment by AlexPoilrouge** [comment]
Huh.

I have never seen this behavior before.
Can you maybe go the extension's settings and tell me the state of your option `Target (locations) display mode` ?

**Comment by jgottlander** [comment]
It's "Available targets only".
When I choose "Discriminate availables", New Zealand, Norway, Sweden, Switzerland and Taiwan are crossed out/strike through, plus some others.
With "Show all (defaults) targets", the list displays just fine.

**Comment by AlexPoilrouge** [comment]
can you share with me the result of a `nordvpn countries` command in your terminal?

also which version or the nordvpn client do you run? ( `nordvpn -v` )

Did you get the extension from github or the gnome extension site?

**Comment by jgottlander** [comment]
`Albania			Canada			France			Indonesia		Mexico			Romania			Sweden			Vietnam
Argentina		Chile			Georgia			Ireland			Moldova			Serbia			Switzerland
Australia		Croatia			Germany			Israel			Netherlands		Singapore		Taiwan
Austria			Cyprus			Greece			Italy			New_Zealand		Slovakia		Thailand
Belgium			Czech_Republic		Hong_Kong		Japan			North_Macedonia		Slovenia		Turkey
Bosnia_And_Herzegovina	Denmark			Hungary			Latvia			Norway			South_Africa		Ukraine
Brazil			Estonia			Iceland			Luxembourg		Poland			South_Korea		United_Kingdom
Bulgaria		Finland			India			Malaysia		Portugal		Spain			United_States`

NordVPN Version 3.7.2

Don't really remember where I installed it from, but I think i cloned the repo, and ran setup.sh.

**Comment by jgottlander** [comment]
I've tried to install from both github and gnome extension site, but both have the same issue.

**Comment by AlexPoilrouge** [comment]
I'm still investigating, but to be honest I'm at loss here. Especially given that I can't reproduce this bug…

I don't see anything obvious mistake in the concerned parts of the code, let alone anything that would make 'W' special…

The extension runs (by default, if no settings changes were made) the following command to check for available countries:
`nordvpn groups | sed -E 's/[^A-Za-z0-9\\-_]+/,/g' | sed -E 's/^,//g'; nordvpn countries | sed -E 's/[^A-Za-z0-9\\-_]+/,/g' | sed -E 's/^,//g'`

If you run it in your terminal, does anything odd shows up? Are there any colors or special formatting displayed?

**Comment by jgottlander** [comment]
This is the output:
```
Africa_The_Middle_East_And_India,Dedicated_IP,P2P,The_Americas
Asia_Pacific,Europe,Standard_VPN_Servers
Albania,Canada,France,Indonesia,Mexico,Romania,S,eden,Vietnam
Argentina,Chile,Georgia,Ireland,Moldova,Serbia,S,itzerland
Australia,Croatia,Germany,Israel,Netherlands,Singapore,Tai,an
Austria,Cyprus,Greece,Italy,Ne,_Zealand,Slovakia,Thailand
Belgium,Czech_Republic,Hong_Kong,Japan,North_Macedonia,Slovenia,Turkey
Bosnia_And_Herzegovina,Denmark,Hungary,Latvia,Nor,ay,South_Africa,Ukraine
Brazil,Estonia,Iceland,Luxembourg,Poland,South_Korea,United_Kingdom
Bulgaria,Finland,India,Malaysia,Portugal,Spain,United_States
```
As you can see, is seems the letter 'w' is replaced with a comma (,) in the affected countries.
I'm not that familiar with sed to troubleshoot the pattern.

**Comment by AlexPoilrouge** [comment]
Well, this is progress since we've pinpoint where the bug is coming from.

Although, there is no apparent reason for this behavior…
I have no clue as to why you're getting this result…

In fact, I've tired running Pop! OS 20.04 on Wayland in a virtual machine, and I still can't reproduce this bug…

Do you use a custom `.bashrc` ?
What languages does your system use (language, formats, keyboard input layout) ?

**Comment by jgottlander** [comment]
I'm running zsh with prezto. Tried running it in bash but same result, also deleted the `.bashrc`. Tried it in in a plain terminal, same result.
Swedish language, no special layouts.

Here is the debug output from sed, if that helps:
```
josef@lenovon> nordvpn countries | sed -E 's/[^A-Za-z0-9\\-_]+/,/g' --debug                                                                                                                                    ~
SED PROGRAM:
  s/[^A-Za-z0-9\\\\-_]+/,/g
INPUT:   'STDIN' line 1
PATTERN: \r-\r  \r\r-\r  \rAlbania\t\t\tCanada\t\t\tFrance\t\t\tIndonesia\t\tMexico\t\t\tRomania\t\t\tSweden\t\t\tVietnam
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
' regex[0] = 0-12 '
PATTERN: ,Albania,Canada,France,Indonesia,Mexico,Romania,S,eden,Vietnam
END-OF-CYCLE:
,Albania,Canada,France,Indonesia,Mexico,Romania,S,eden,Vietnam
INPUT:   'STDIN' line 2
PATTERN: Argentina\t\tChile\t\t\tGeorgia\t\t\tIreland\t\t\tMoldova\t\t\tSerbia\t\t\tSwitzerland
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 9-11 '		'
PATTERN: Argentina,Chile,Georgia,Ireland,Moldova,Serbia,S,itzerland
END-OF-CYCLE:
Argentina,Chile,Georgia,Ireland,Moldova,Serbia,S,itzerland
INPUT:   'STDIN' line 3
PATTERN: Australia\t\tCroatia\t\t\tGermany\t\t\tIsrael\t\t\tNetherlands\t\tSingapore\t\tTaiwan
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 9-11 '		'
PATTERN: Australia,Croatia,Germany,Israel,Netherlands,Singapore,Tai,an
END-OF-CYCLE:
Australia,Croatia,Germany,Israel,Netherlands,Singapore,Tai,an
INPUT:   'STDIN' line 4
PATTERN: Austria\t\t\tCyprus\t\t\tGreece\t\t\tItaly\t\t\tNew_Zealand\t\tSlovakia\t\tThailand
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 7-10 '			'
PATTERN: Austria,Cyprus,Greece,Italy,Ne,_Zealand,Slovakia,Thailand
END-OF-CYCLE:
Austria,Cyprus,Greece,Italy,Ne,_Zealand,Slovakia,Thailand
INPUT:   'STDIN' line 5
PATTERN: Belgium\t\t\tCzech_Republic\t\tHong_Kong\t\tJapan\t\t\tNorth_Macedonia\t\tSlovenia\t\tTurkey
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 7-10 '			'
PATTERN: Belgium,Czech_Republic,Hong_Kong,Japan,North_Macedonia,Slovenia,Turkey
END-OF-CYCLE:
Belgium,Czech_Republic,Hong_Kong,Japan,North_Macedonia,Slovenia,Turkey
INPUT:   'STDIN' line 6
PATTERN: Bosnia_And_Herzegovina\tDenmark\t\t\tHungary\t\t\tLatvia\t\t\tNorway\t\t\tSouth_Africa\t\tUkraine
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 22-23 '	'
PATTERN: Bosnia_And_Herzegovina,Denmark,Hungary,Latvia,Nor,ay,South_Africa,Ukraine
END-OF-CYCLE:
Bosnia_And_Herzegovina,Denmark,Hungary,Latvia,Nor,ay,South_Africa,Ukraine
INPUT:   'STDIN' line 7
PATTERN: Brazil\t\t\tEstonia\t\t\tIceland\t\t\tLuxembourg\t\tPoland\t\t\tSouth_Korea\t\tUnited_Kingdom
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 6-9 '			'
PATTERN: Brazil,Estonia,Iceland,Luxembourg,Poland,South_Korea,United_Kingdom
END-OF-CYCLE:
Brazil,Estonia,Iceland,Luxembourg,Poland,South_Korea,United_Kingdom
INPUT:   'STDIN' line 8
PATTERN: Bulgaria\t\tFinland\t\t\tIndia\t\t\tMalaysia\t\tPortugal\t\tSpain\t\t\tUnited_States
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 8-10 '		'
PATTERN: Bulgaria,Finland,India,Malaysia,Portugal,Spain,United_States
END-OF-CYCLE:
Bulgaria,Finland,India,Malaysia,Portugal,Spain,United_States
```

**Comment by jgottlander** [comment]
I'm running zsh with prezto. Tried running it in bash but same result, also deleted the `.bashrc`. Tried it in in a plain terminal, same result.
Swedish language, no special layouts.

Here is the debug output from sed, if that helps:
```
josef@lenovon> nordvpn countries | sed -E 's/[^A-Za-z0-9\\-_]+/,/g' --debug                                                                                                                                    ~
SED PROGRAM:
  s/[^A-Za-z0-9\\\\-_]+/,/g
INPUT:   'STDIN' line 1
PATTERN: \r-\r  \r\r-\r  \rAlbania\t\t\tCanada\t\t\tFrance\t\t\tIndonesia\t\tMexico\t\t\tRomania\t\t\tSweden\t\t\tVietnam
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
' regex[0] = 0-12 '
PATTERN: ,Albania,Canada,France,Indonesia,Mexico,Romania,S,eden,Vietnam
END-OF-CYCLE:
,Albania,Canada,France,Indonesia,Mexico,Romania,S,eden,Vietnam
INPUT:   'STDIN' line 2
PATTERN: Argentina\t\tChile\t\t\tGeorgia\t\t\tIreland\t\t\tMoldova\t\t\tSerbia\t\t\tSwitzerland
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 9-11 '		'
PATTERN: Argentina,Chile,Georgia,Ireland,Moldova,Serbia,S,itzerland
END-OF-CYCLE:
Argentina,Chile,Georgia,Ireland,Moldova,Serbia,S,itzerland
INPUT:   'STDIN' line 3
PATTERN: Australia\t\tCroatia\t\t\tGermany\t\t\tIsrael\t\t\tNetherlands\t\tSingapore\t\tTaiwan
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 9-11 '		'
PATTERN: Australia,Croatia,Germany,Israel,Netherlands,Singapore,Tai,an
END-OF-CYCLE:
Australia,Croatia,Germany,Israel,Netherlands,Singapore,Tai,an
INPUT:   'STDIN' line 4
PATTERN: Austria\t\t\tCyprus\t\t\tGreece\t\t\tItaly\t\t\tNew_Zealand\t\tSlovakia\t\tThailand
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 7-10 '			'
PATTERN: Austria,Cyprus,Greece,Italy,Ne,_Zealand,Slovakia,Thailand
END-OF-CYCLE:
Austria,Cyprus,Greece,Italy,Ne,_Zealand,Slovakia,Thailand
INPUT:   'STDIN' line 5
PATTERN: Belgium\t\t\tCzech_Republic\t\tHong_Kong\t\tJapan\t\t\tNorth_Macedonia\t\tSlovenia\t\tTurkey
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 7-10 '			'
PATTERN: Belgium,Czech_Republic,Hong_Kong,Japan,North_Macedonia,Slovenia,Turkey
END-OF-CYCLE:
Belgium,Czech_Republic,Hong_Kong,Japan,North_Macedonia,Slovenia,Turkey
INPUT:   'STDIN' line 6
PATTERN: Bosnia_And_Herzegovina\tDenmark\t\t\tHungary\t\t\tLatvia\t\t\tNorway\t\t\tSouth_Africa\t\tUkraine
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 22-23 '	'
PATTERN: Bosnia_And_Herzegovina,Denmark,Hungary,Latvia,Nor,ay,South_Africa,Ukraine
END-OF-CYCLE:
Bosnia_And_Herzegovina,Denmark,Hungary,Latvia,Nor,ay,South_Africa,Ukraine
INPUT:   'STDIN' line 7
PATTERN: Brazil\t\t\tEstonia\t\t\tIceland\t\t\tLuxembourg\t\tPoland\t\t\tSouth_Korea\t\tUnited_Kingdom
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 6-9 '			'
PATTERN: Brazil,Estonia,Iceland,Luxembourg,Poland,South_Korea,United_Kingdom
END-OF-CYCLE:
Brazil,Estonia,Iceland,Luxembourg,Poland,South_Korea,United_Kingdom
INPUT:   'STDIN' line 8
PATTERN: Bulgaria\t\tFinland\t\t\tIndia\t\t\tMalaysia\t\tPortugal\t\tSpain\t\t\tUnited_States
COMMAND: s/[^A-Za-z0-9\\\\-_]+/,/g
MATCHED REGEX REGISTERS
  regex[0] = 8-10 '		'
PATTERN: Bulgaria,Finland,India,Malaysia,Portugal,Spain,United_States
END-OF-CYCLE:
Bulgaria,Finland,India,Malaysia,Portugal,Spain,United_States
```

**Comment by AlexPoilrouge** [comment]
Okay, so after investigation I was able to reproduce this bug in a virtual environment and in does indeed occur on your configuration when your language ( `settings` -> `region & language` -> `language`)  is set to "swedish"…

That being said, I don't know why this affect the behavior of the `sed` command. 
In fact, when in a terminal I run:
`echo sweden | sed 's/[a-z]/,/g'` in a terminal, I get `,w,,,,`. (can you confirm?)

This is an unexpected behavior, but at least we've made a step forward.

I'll try and see if I can integrate a way around this problem.

**Comment by jgottlander** [comment]
Yep, this is what I get:
`,w,,,,`

**Comment by AlexPoilrouge** [comment]
Okay,

I may finally have a fix for your bug. It seems to work on my virtual environment, so hopefully it'll work on your system too.

Can you test out the latest commit on the master branch, and tell me if that fixes it?

**Comment by jgottlander** [comment]
That fixes it! Nice work :)
