### ISSUE TITLE
Menubar icon does not change displayed status unless clicked

### ISSUE THREAD

**Issue by zaneselvans** [AlexPoilrouge/NordVPN-connect#18]
At some point recently (I don't recall exactly when / what version) the menubar icon displaying the NordVPN status stopped updating automatically when the VPN connection status changes. This is true when I connect or disconnect from NordVPN using the nordvpn command line tool, or when I connect to NordVPN using the extension. Disconnecting from NordVPN using the menu item does update the visual status indicator.

One of the things I really liked about the extension was having an always visible indicator of the VPN status, and this change kind of negates that feature, since I have to click on the menu bar to ensure that the displayed status is current.

Just wondering if this is something you've come across before and whether there's some easy fix.  Thanks for making the extension!

I'm on Ubuntu 20.04.01, with Gnome 3.36.4, NordVPN 3.7.4, and NordVPN Connect version 14.

**Comment by kev005** [comment]
Seeing same in MANJARO x86_64 20.2 Nibia with  GNOME 3.38, Nordvpn 3.8.7, and Nordvpn Connect version 1.72 from AUR.  Also, not able to open the options menu (3-dots) if I have added a subnet on the whitelist so I can access my local shares.

**Comment by bernard-vital** [comment]
Exactly the same on Ubuntu 20.04 up-to-date

**Comment by chrisduran** [comment]
I have come across the same problem. I've narrowed it down a little: I get this behaviour when the Technology is changed to NordLynx.

If the technology is OpenVPN - the menubar icon will update the status to connected without interaction. If the technology is NordLynx, I need to click on the menubar icon for it to update the status to connected

**Comment by chrisduran** [comment]
Solved the problem: Under the extension Advanced settings, the default command for 'Checking that the connection to the VPN is online' is incorrect.

The default setting is: `ifconfig -a | grep -E '(nordvpn|tun0)'"`
The correct setting should be `ifconfig -a | grep -E '(nordlynx|tun0)'"`

Changing the setting to the above results in the menubar icon changing for both technologies.

**Comment by zaneselvans** [comment]
Yes! That totally fixed it. Thank you for debugging!

**Comment by AlexPoilrouge** [comment]
Thank you @chrisduran .
