### ISSUE TITLE
Settings menu question

### ISSUE THREAD

**Issue by sandervankasteel** [AlexPoilrouge/NordVPN-connect#2]
Hi, I have a quick question about one of your items on your ToDo list;

`Add a 'settings' page for this extension.`

Would you accept a PR with simple settings page in it? One the things I would personally like to see, is showing an icon only for example.

**Comment by AlexPoilrouge** [comment]
Hi.
I have been working on just that.

Although it also comes with, let say "(even) more hazardous" features, that I don't want to publish on Master (and therefore the AUR) just yet.
But, if you want, I have just uploaded my 'dev' branch which is up-to-date on my work. It comes with what I think you want: a settings page containing (amongst other things) a "compact icon" mode you can toggle.

**Comment by sandervankasteel** [comment]
Yeah I can totally get why you don't want to publish that on the `master` branch directly. The `master` branch should only be used for "production ready code" 

I will checkout your `dev ` branch :) Thanks! :tada:

**Comment by AlexPoilrouge** [comment]
I have pushed the changes into the `master` branch.
Can you confirm that this is close enough to what you wanted?

**Comment by sandervankasteel** [comment]
Thanks @AlexPoilrouge this exactly what I wanted :+1:
