### ISSUE TITLE
"No JS module 'tweener' found in search path

### ISSUE THREAD

**Issue by ChTBoner** [AlexPoilrouge/NordVPN-connect#21]
Hi, 

I have this error using GNOME Shell 3.38.1

![image](https://user-images.githubusercontent.com/14848356/95683912-502a3f00-0bee-11eb-98bc-bfbb843d1b62.png)

Please let me know if you need any more info.

Thanks for your work.

**Comment by AlexPoilrouge** [comment]
Patched
