### ISSUE TITLE
Nordvpn Official Icons

### ISSUE THREAD

**Issue by ruanformigoni** [AlexPoilrouge/NordVPN-connect#29]
Hi, would you be interested to use the official nordvpn icon in the main repo, with blue/grayed-out colors to indicated status?

![nvpn-off](https://user-images.githubusercontent.com/18180693/124068813-92f8a500-da11-11eb-8325-5e81f7994fef.png)
![nvpn-on](https://user-images.githubusercontent.com/18180693/124068815-9429d200-da11-11eb-8bf4-9478e8d35524.png)

Thanks,

Ruan

**Comment by AlexPoilrouge** [comment]
Hi.

I have no ties whatsoever to NordVPN, and I usually try to use as little intellectual property as I can.

So no, sorry, I'm not really interested.
