### ISSUE TITLE
The login check is not working with 3.12.0

### ISSUE THREAD

**Issue by hellia-be** [AlexPoilrouge/NordVPN-connect#31]
Using version 3.12.0 of the nordvpn-cli tool, the login check of the extension is not working anymore.
The new behavior is that the tool lets you log in and only after that it tells you whether you are already logged in or not.
It should be possible to bypass this when using the login --nordaccount option which is set to become the default in the future.

Furthermore, while debugging this, I noticed that I can't overwrite any of the commands in the advanced section even after enabling the toggle at the top.

Do let me know if you need more details.

**Comment by Rulz2003** [comment]
I've got this working by editing the advanced section of the extension, and adding the --nordaccount setting. In short,  the default setting should look like this

`echo '' | nordvpn login --nordaccount | grep -Po 'already logged'.`

@hellia-be - It happened to me first that I couldn't find the apply button at the bottom of the screen

**Comment by hellia-be** [comment]
I solved it in the same way.
For me, I was not able to type in the boxes in the advanced tab so I had to cut it out, edit it somewhere else and paste it back.

**Comment by AlexPoilrouge** [comment]
Thanks for reporting and finding a fix. I wasn't even aware of the nordvpn client's update, and this saves me a lot of time. I'll patch this asap.

**Comment by Mladia** [comment]
I am still getting not logged in on the tool. I am running the current version from the Gnome Extension website. 

```
➜  nordvpn -v      
NordVPN Version 3.12.3

➜  echo '' | nordvpn login --nordaccount | grep -Po 'already logged'
already logged

 ➜  nordvpn login --nordaccount
You are already logged in.

 ✘1 ➜  nordvpn login              
You are already logged in.

```
After I connect through the cli, the extension properly displays the status.
