### ISSUE TITLE
Not compatible with Gnome 42 (Ubuntu 22.04 LTS)

### ISSUE THREAD

**Issue by leinardi** [AlexPoilrouge/NordVPN-connect#34]
The extension is not compatible with the latest stable version of Gnome:
![image](https://user-images.githubusercontent.com/273338/161421766-5911c5e7-1eeb-43fa-88ac-db374e90257b.png)

https://extensions.gnome.org/extension/1595/nordvpn-connect/

To reproduce the issue try to install the extension on Ubuntu 22.04 LTS.

**Comment by mrnrod45** [comment]
I too Encountered an Issues with Gnome 42 on Arch I just believe he needs to update the extension and should be fine

**Comment by Manni1000** [comment]
i hope they update the extension soon because it was so usful

**Comment by sc44** [comment]
@SirRhynus
Worked thanks a lot.

**Comment by aliris-schmidt** [comment]
Installed it manually in Ubuntu 22.04. After the next logout the extension was "updated" to the incompatible version from extensions.gnome.org.

**Comment by leinardi** [comment]
Yeah, I don't think this ticket should be closed until the extension is still marked as Incomparable with Gnome Shell 42 here:
https://extensions.gnome.org/extension/1595/nordvpn-connect/

**Comment by sc44** [comment]
Hello, extensions.gnome.org version is 18 not 19.
Change in metadata.json  to "version": 18 and setup.sh --gitless.
When extensions.gnome.org is updated you receive version 19.

**Comment by titov-vv** [comment]
@AlexPoilrouge, yes, I can install extension from git, but could you please update it on https://extensions.gnome.org/extension/1595/nordvpn-connect/ as well? (My understanding - only the owner can do it) Many people use it as a centralized source, this is the reason for inquiry.

**Comment by AlexPoilrouge** [comment]
I apologize, but a gnome developper suddenly decided that, despite very little changes, version 19 code stopped matching gnome's standards.

So this'll take time I barely have.

**Comment by fdaciuk** [comment]
@AlexPoilrouge can you share the feedback you've received from the gnome developer? Maybe we can help you with this update :)

**Comment by AlexPoilrouge** [comment]
@fdaciuk Sorry,

be my guest, if you really want to look into it:

```
1. Use initTranslations() and getSettings() from ExtensionUtils instead of creating your own custom functions:
    https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/misc/extensionUtils.js
    
2. Also do this on disable:

    ```js
    _indicator = null;
    SETTINGS = null;
    SubMenus = null;
    ```

3. Lang is a deprecated module. Please remove it for the next version:
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#general-advice
    Learn how to remove Lang from your code:
    https://gjs.guide/guides/gjs/legacy-class-syntax.html

4. You cannot create objects in global scope (prefs.js line 14).
    Move that line to `buildPrefsWidget` as local.
    You can pass it to `NVPN_Settings` as dependency injection.

5. Log should be only available in debug mode:
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#no-excessive-logging

6. You cannot create objects in global scopes (line 28 subMenus.js):
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#only-use-init-for-initialization

If you need any help with your extension you can ask us on:
- [GNOME Matrix Channel](https://matrix.to/#/#extensions:gnome.org)
- IRC Bridge: irc://irc.gimpnet.org/shell-extensions

Please use the review page to follow up:

https://extensions.gnome.org/review/32153
```
