### ISSUE TITLE
Error with /usr/bin/bash

### ISSUE THREAD

**Issue by ddnexus** [AlexPoilrouge/NordVPN-connect#4]
The extension should check whether bash is at `/usr/bin/bash` or somewhere else. I had to add a symlink in order to make it work.

**Comment by AlexPoilrouge** [comment]
Changes pushed to the master branch:
- default 'shell' value set to `/bin/bash`
- said 'shell' value is now editable from the extension settings pages
- message should appear if said value matches a non existing path

**Comment by ddnexus** [comment]
Thank you!
