### ISSUE TITLE
Compact icon?

### ISSUE THREAD

**Issue by ddnexus** [AlexPoilrouge/NordVPN-connect#5]
Which is the compact icon? I see a generic "No" symbol. Is that the compact icon?

**Comment by AlexPoilrouge** [comment]
Some people would prefer to not have the "NVPN" tag in their top panel, wanting the extension to take as little place as possible.
'Compact icon' mode (probably awkwardly named), just gets rid of the tag.

Should look like this:

![nvpn-compact-ex](https://user-images.githubusercontent.com/2669900/58479588-dc060d00-8158-11e9-9753-a9cd83310304.png)

**Comment by ddnexus** [comment]
Yes, I discovered that after I actually connected. Thank you. 

FYI, the tag is misaligned from the icon if you use some extension like DashToPanel that can change the height of the panel. 

![image](https://user-images.githubusercontent.com/100721/58481295-4da88000-8186-11e9-96d0-9f2732e0a432.png)

**Comment by AlexPoilrouge** [comment]
Thanks for reporting this.

I'll look into it.

**Comment by AlexPoilrouge** [comment]
A fix that should keep the 'NVPN' tag correctly aligned vertically has been pushed onto the master branch.

**Comment by ddnexus** [comment]
You fast! Thank you!
